################################################################################
# training parameters
################################################################################
train:
  pipeline: "res"       #  "res" "fid" "hard"
  act: "Hardswish"      #  "SiLU" "Hardswish" "LeakyReLU"
  loss: "xentropy"      #   must be either xentropy or iou
  aux_loss: True
  lamda: 1.0
  scheduler: "consine"  # "consine" or "decay"
  max_epochs: 100
  consine:
    min_lr: 0.0001
    max_lr: 0.01
    first_cycle: 50
    cycle: 1
    wup_epochs: 1
    gamma: 1.0
  decay:
    lr: 0.01
    wup_epochs: 1        # warmup during first XX epochs (can be float)
    lr_decay: 0.99       # learning rate decay per epoch after initial cycle (from min lr)
  momentum: 0.9          # sgd momentum
  w_decay: 0.0001        # weight decay
  batch_size: 6          # batch size (was at 6 initially)
  report_batch: 100      # every x batches, report loss
  report_epoch: 1        # every x epochs, report validation set
  epsilon_w: 0.001       # class weight w = 1 / (content + epsilon_w)
  save_summary: False    # Summary of weight histograms for tensorboard   Must false since not check the api
  save_scans:  False     # False doesn't save anything, True saves som
  show_scans: True       # show scans during training
  save_batch: 50
  workers: 6             # number of threads to get data (was 6 initially)

################################################################################
# postproc parameters
################################################################################
post:
  KNN:
    use: True # This parameter default is false
#     params:
#       knn: 5
#       search: 5
#       sigma: 1.0
#       cutoff: 1.0
    params:
      knn: 7
      search: 7
      sigma: 1.0
      cutoff: 2.0

################################################################################
# dataset (to find parser)
################################################################################
dataset:
  labels: "kitti"
  scans: "kitti"
  max_points: 150000 # max of any scan in dataset
  sensor:
    name: "ouster64"
    type: "spherical" # projective
    fov_up: 30.5
    fov_down: -22.5
    img_prop:
      width: 512
      height: 64