datasets:
  KITTI_360:
    enabled: false
    use_multiprocessing: true
    root_path: "/media/donceykong/donceys_data_ssd/datasets/KITTI-360"
    sequences: [0, 2, 3, 4, 5, 6, 7, 9, 10]

  CU_MULTI:
    enabled: true
    use_multiprocessing: true
    root_path: "/media/donceykong/donceys_data_ssd/datasets/CU_MULTI/data"
    osm_file_path: "/media/donceykong/donceys_data_ssd/datasets/CU_MULTI/data"
    environments: ["main_campus", "kittredge_loop"]
    robots: ["robot1", "robot2", "robot3", "robot4"]