# This file is covered by the LICENSE file in the root of this project.
name: "kitti360"
labels:
  0: "unlabeled"
  1: "ego vehicle"
  2: "rectification border"
  3: "out of roi"
  4: "static"
  5: "dynamic"
  6: "ground"
  7: "road"
  8: "sidewalk"
  9: "parking"
  10: "rail track"
  11: "building"
  12: "wall"
  13: "fence"
  14: "guard rail"
  15: "bridge"
  16: "tunnel"
  17: "pole"
  18: "polegroup"
  19: "traffic light"
  20: "traffic sign"
  21: "vegetation"
  22: "terrain"
  23: "sky"
  24: "person"
  25: "rider"
  26: "car"
  27: "truck"
  28: "bus"
  29: "caravan"
  30: "trailer"
  31: "train"
  32: "motorcycle"
  33: "bicycle"
  34: "garage"
  35: "gate"
  36: "stop"
  37: "smallpole"
  38: "lamp"
  39: "trash bin"
  40: "vending machine"
  41: "box"
  42: "unknown construction"
  43: "unknown vehicle"
  44: "unknown object"
  45: "OSM Building"
  46: "OSM Road"
color_map: # bgr
  0: [0, 0, 0]
  1: [0, 0, 0]
  2: [0, 0, 0]
  3: [0, 0, 0]
  4: [0, 0, 0]
  5: [111, 74, 0]
  6: [81, 0, 81]
  7: [128, 64, 128]
  8: [244, 35, 232]
  9: [250, 170, 160]
  10: [230, 150, 140]
  11: [0, 100, 0]
  12: [102, 102, 156]
  13: [190, 153, 153]
  14: [180, 165, 180]
  15: [150, 100, 100]
  16: [150, 120, 90]
  17: [153, 153, 153]
  18: [153, 153, 153]
  19: [250, 170, 30]
  20: [220, 220, 0]
  21: [107, 142, 35]
  22: [152, 251, 152]
  23: [70, 130, 180]
  24: [220, 20, 60]
  25: [255, 0, 0]
  26: [0, 0, 142]
  27: [0, 0, 70]
  28: [0, 60, 100]
  29: [0, 0, 90]
  30: [0, 0, 110]
  31: [0, 80, 100]
  32: [0, 0, 230]
  33: [119, 11, 32]
  34: [64, 128, 128]
  35: [190, 153, 153]
  36: [150, 120, 90]
  37: [153, 153, 153]
  38: [0, 64, 64]
  39: [0, 128, 192]
  40: [128, 64, 0]
  41: [64, 64, 128]
  42: [102, 0, 0]
  43: [51, 0, 51]
  44: [32, 32, 32]
  45: [255, 255, 255] # OSM Building
  46: [0, 0, 255] # OSM Road

content: # as a ratio with the total number of points
  0: 0.2943666527148891
  1: 0.0
  2: 0.0
  3: 0.0
  4: 0.0
  5: 0.0
  6: 0.03899204748677752
  7: 0.2195597580000761
  8: 0.019614930938700963
  9: 0.006420988546858948
  10: 0.0
  11: 0.00033294014687416766
  12: 0.0
  13: 0.0
  14: 0.0
  15: 0.0
  16: 0.0
  17: 0.0032057379856169858
  18: 0.0
  19: 0.0
  20: 0.0004090407518739774
  21: 0.10163235797724592
  22: 0.05532513983486169
  23: 0.0
  24: 0.0
  25: 0.0
  26: 0.1508409116852479
  27: 0.0
  28: 0.0
  29: 0.0
  30: 0.0
  31: 0.0
  32: 0.0
  33: 0.0
  34: 0.0005422168106236445
  35: 0.0
  36: 0.0
  37: 0.0006183174156234542
  38: 0.0
  39: 0.0
  40: 0.0
  41: 0.0
  42: 0.0
  43: 0.0
  44: 0.0
  45: 0.02993607549180016     # OSM Building
  46: 0.014535215554963662    # OSM Road

# classes that are indistinguishable from single scan or inconsistent in
# ground truth are mapped to their closest equivalent
learning_map:
  0: 0      # "unlabeled"
  1: 1      # "ego vehicle" mapped to "car"
  2: 0      # "rectification border" mapped to "unlabeled"
  3: 0      # "out of roi" mapped to "unlabeled"
  4: 0      # "static" mapped to "unlabeled"
  5: 0      # "dynamic" mapped to "unlabeled"
  6: 0      # "ground" mapped to "unlabeled"
  7: 2      # "road"
  8: 12     # Sidewalk mapped to itself
  9: 12     # "parking" mapped to itself
  10: 0     # "rail track" mapped to "unlabeled"
  11: 3     # "building" mapped to itself
  12: 0     # "wall" mapped to "unlabeled"
  13: 6     # "fence" mapped to itself
  14: 13    # "guard rail" mapped to Fence
  15: 0     # "bridge" mapped to "unlabeled"
  16: 0     # "tunnel" mapped to "unlabeled"
  17: 4     # "pole"
  18: 4     # "polegroup" mapped to "unlabeled"
  19: 4     # "traffic light"
  20: 4     # "traffic sign"
  21: 11    # "vegetation"
  22: 10    # "terrain"
  23: 0     # "sky" mapped to "unlabeled"
  24: 9     # "person"
  25: 7     # "rider"
  26: 1     # "car"
  27: 1     # "truck"
  28: 1     # "bus" mapped to "other-vehicle"
  29: 1     # "caravan" mapped to "other-vehicle"
  30: 1     # "trailer" mapped to "other-vehicle"
  31: 1     # "train" mapped to "other-vehicle"
  32: 1     # "motorcycle"
  33: 5     # "bicycle"
  34: 3     # "garage" mapped to building
  35: 6     # "gate" mapped to "fence"
  36: 4     # "stop" mapped to "pole"
  37: 4     # "smallpole" mapped to "pole"
  38: 4     # "lamp" mapped to "unlabeled"
  39: 0     # "trash bin" mapped to "unlabeled"
  40: 0     # "vending machine" mapped to "unlabeled"
  41: 0     # "box" mapped to "unlabeled"
  42: 0     # "unknown construction" mapped to "unlabeled"
  43: 0     # "unknown vehicle" mapped to "unlabeled"
  44: 0     # "unknown object" mapped to "unlabeled"
  45: 7     # OSM road points mapped to itself
  46: 8     # OSM building points mapped to itself
learning_map_inv: # inverse of previous map
  0: 0      # "unlabeled", and others ignored
  1: 26     # Car
  2: 7      # Road
  3: 11     # Building
  4: 13     # Pole
  5: 33     # Bicycle
  6: 13     # Fence
  7: 45     # OSM ROAD
  8: 46     # OSM Building
  9: 24     # Person
  10: 22    # Terrain
  11: 24    # Vegitation
  12: 9     # Parking
  13: 8     # Sidewalk
learning_ignore: # Ignore classes
  0: True     # "unlabeled", and others ignored
  1: False    # Car
  2: False    # Road
  3: False    # Building
  4: False    # Pole
  5: False    # Bicycle
  6: False    # Fence
  7: False    # OSM Road
  8: False    # OSM Building
  9: False    # Person
  10: False   # Terrain
  11: False   # Vegitation
  12: False   # Parking
  13: False   # Sidewalk
split: # sequence numbers
  train:
    - 0
  valid:
    - 0
  test:
    - 0
  # train:
  #   - 0
  #   - 4
  #   - 5
  #   - 6
  #   - 9
  #   - 10
  # valid:
  #   - 2
  # test:
  #   - 7