# TODO: Use dataset_name to determine paths of other fields
dataset_path: /media/donceykong/donceys_data_ssd/datasets/CU_MULTI/data
dataset_name: CU-MULTI     # "KITTI-360" or "CU-MULTI"
infer_or_train: train       # "train" or "infer"
data_config: /home/donceykong/Desktop/ARPG/projects/fall_2024/Lidar2OSM_FULL/Lidar2OSM/lidar2osm/config/data_cfg_kitti360.yaml


training:
  model_path: /media/donceykong/donceys_data_ssd/models/CENet/cumulti_osm_style
  model_name: cenet_osm-512
  use_progressive_growing: True

  model_configs:
    cenet_osm-512:
      arch_config: /home/donceykong/Desktop/ARPG/projects/fall_2024/Lidar2OSM_FULL/Lidar2OSM/lidar2osm/config/arch/train/cenet_osm-512.yaml
      model_name: cenet_osm-512

    cenet_osm-1024:
      arch_config: /home/donceykong/Desktop/ARPG/projects/fall_2024/Lidar2OSM_FULL/Lidar2OSM/lidar2osm/config/arch/train/cenet_osm-1024p.yaml
      model_name: cenet_osm-1024
      pretrained_model_path: /media/donceykong/donceys_data_ssd/models/CENet/cumulti_osm_style/cenet_osm-512

    cenet_osm-2048:
      arch_config: /home/donceykong/Desktop/ARPG/projects/fall_2024/Lidar2OSM_FULL/Lidar2OSM/lidar2osm/config/arch/train/cenet_osm-2048p.yaml
      model_name: cenet_osm-2048
      pretrained_model_path: /media/donceykong/donceys_data_ssd/models/CENet/cumulti_osm_style/cenet_osm-1024